CREATE TABLE public.messages (
    id bigint NOT NULL,
    content character varying(1000) NOT NULL,
    sender_id bigint,
    "timestamp" timestamp(6) without time zone
);

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.poster_images (
    poster_id bigint NOT NULL,
    image_url character varying(255)
);

CREATE TABLE public.posters (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(1000),
    image_url character varying(255),
    location character varying(255),
    price character varying(255),
    tags character varying(255),
    title character varying(255) NOT NULL,
    category character varying(255),
    email character varying(255),
    full_description character varying(3000),
    image character varying(255),
    likes integer,
    phone character varying(255),
    saved boolean,
    type character varying(255),
    updated_at timestamp(6) without time zone
);

ALTER TABLE public.posters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    id bigint NOT NULL,
    username character varying(255)
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.posters
    ADD CONSTRAINT posters_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY public.poster_images
    ADD CONSTRAINT fk15c9evwoede25an3nt21xt5dn FOREIGN KEY (poster_id) REFERENCES public.posters(id);
