--
-- PostgreSQL database dump
--

\restrict 7ufhtwyEXD0L0a1pZ2Pw60lQ2sdI7b26m4npPZj02gEeNShnRrbC2EzK97cbEGK

-- Dumped from database version 15.14 (Debian 15.14-1.pgdg13+1)
-- Dumped by pg_dump version 15.14 (Debian 15.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    content character varying(1000) NOT NULL,
    sender_id bigint,
    "timestamp" timestamp(6) without time zone
);


--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: poster_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.poster_images (
    poster_id bigint NOT NULL,
    image_url character varying(255)
);


--
-- Name: posters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.posters (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(1000),
    image_url character varying(255),
    location character varying(255),
    price character varying(255),
    tags character varying(255),
    title character varying(255) NOT NULL,
    category character varying(255),
    email character varying(255),
    full_description character varying(3000),
    image character varying(255),
    likes integer,
    phone character varying(255),
    saved boolean,
    type character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: posters_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.posters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    id bigint NOT NULL,
    username character varying(255)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: posters posters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posters
    ADD CONSTRAINT posters_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: poster_images fk15c9evwoede25an3nt21xt5dn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.poster_images
    ADD CONSTRAINT fk15c9evwoede25an3nt21xt5dn FOREIGN KEY (poster_id) REFERENCES public.posters(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 7ufhtwyEXD0L0a1pZ2Pw60lQ2sdI7b26m4npPZj02gEeNShnRrbC2EzK97cbEGK

