CREATE TABLE public.likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    poster_id BIGINT NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_poster FOREIGN KEY (poster_id) REFERENCES public.posters(id) ON DELETE CASCADE,
    CONSTRAINT unique_user_poster UNIQUE (user_id, poster_id)
);