CREATE TABLE public.comments (
    id BIGINT NOT NULL,
    content VARCHAR(1000) NOT NULL,
    poster_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

-- Add IDENTITY for auto-increment
ALTER TABLE public.comments 
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Primary key
ALTER TABLE ONLY public.comments
ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

-- Foreign keys
ALTER TABLE ONLY public.comments
ADD CONSTRAINT fk_comments_poster FOREIGN KEY (poster_id) REFERENCES public.posters(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.comments
ADD CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
